# Generated by Django 5.0.6 on 2024-05-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('AW', models.JSONField()),
                ('AB', models.JSONField()),
                ('SZ', models.CharField(max_length=10)),
                ('SOL', models.JSONField()),
                ('C', models.CharField(max_length=255)),
            ],
        ),
    ]
