# Generated by Django 5.0.6 on 2024-05-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go_problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='nextToPlay',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White')], default='black', max_length=5),
        ),
    ]
