# Generated by Django 5.0.6 on 2024-06-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go_problems', '0003_problem_pk_user_alter_problem_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
