# Generated by Django 5.0.6 on 2024-06-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go_problems', '0004_problem_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='C',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
